### ISSUE TITLE
mip-audio预览效果消失

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/www.mipengine.org#14]
https://www.mipengine.org/examples/mip-extensions/mip-audio.html

**Comment by xuexb** [comment]
这是由于在 [MIP 扩展组件规范](https://github.com/mipengine/mip-extensions/blob/master/docs/spec-readme-md.md) 文档中代码块加了 `html` 标记，并且 [mip-cli](https://github.com/mipengine/mip-cli) 生成的组件内也包含该标识，我在处理预览按钮时判断了只有添加 `html` 标记的才插入预览按钮。

代码：

<https://github.com/mipengine/www.mipengine.org/blob/a31de7dc8b6e48de13b4bc06b3155d22d9065974/scripts/filter.priview.js#L22-L24>

修改方案：

1. 修改该组件的文档，添加 `html` 标记。
2. 修改官网编译脚本，去掉 `html` 的判断，这样可能导致在组件文档中随意使用代码块都将有预览按钮，比如想输出一段 JS 片段。 

@wupengFEX 你怎么看？我看你的 [mip-bind 文档](https://raw.githubusercontent.com/mipengine/mip-extensions/master/src/mip-bind/README.md) 代码中就存在需要输出代码块，但不要预览的功能。

**Comment by wupengFEX** [comment]
@xuexb 我觉得还是以html标记的加预览合理点，否则正常输出代码都不方便了，文档预览有问题点可以统一改一版。
