### ISSUE TITLE
MIP Cache文档细化 过期时间说明

### ISSUE THREAD

**Issue by jennyliang220** [mipengine/www.mipengine.org#43]
https://www.mipengine.org/doc/2-tech/3-mip-cache.html

### MIP Cache 常规更新机制
MIP Cache 常规更新机制也是页面最常规，最常用的更新机制。目前页面最短更新周期 52 分钟，

改为：博客的内容，说得更清晰：http://www.cnblogs.com/mipengine/p/why_mip-cache_exists.html

> 考虑到站长有更新页面的需求，MIP-Cache 会定期重新抓取 MIP 页并进行校验。
> 在 MIP-Cache 中：
>页面的缓存时间为52分钟-5天（由该页面用户点击量和站点本身稳定性决定）。
图片缓存时间为10天。
MIP-JS 组件文件的缓存时间为10分钟。
在当前文件过期后，MIP-Cache 会重新抓取资源。如果是 HTML 页面，MIP-Cache 还会对页面文件进行 MIP 规范校验。如果此时页面内容不再符合 MIP 规范，MIP-Cache 就不再缓存这个页面了。这样，所有 MIP-Cache 中的页面都是最新的，并且符合 MIP 规范。
> 如果要快速清理 MIP-Cache 内容，请参考站长平台 MIP-Cache 说明。注意，对于同一个站点，每100秒最多清理10条。

**Comment by xuexb** [comment]
欢迎 PR ~
